from MySQLdb import Error
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QDialog
import MySQLdb as mdb


def dbret():
    try:
        db = mdb.connect('localhost', 'root', '2173', 'mydb')
        return db
    except mdb.Error as e:
        print(f'Error: {e}')


class addDialog(QDialog):
    def __init__(self, parent=None):
        super(addDialog, self).__init__(parent)
        self.setObjectName("Dialog")
        self.resize(898, 419)
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=self)
        self.spinBox.setMinimum(-999999999)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=self)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtTop)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_2.setMinimum(-999999999)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_3.addWidget(self.spinBox_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.spinBox_3 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_3.setMinimum(-999999999)
        self.spinBox_3.setMaximum(999999999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_4.addWidget(self.spinBox_3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.spinBox_4 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_4.setMinimum(-999999999)
        self.spinBox_4.setMaximum(999999999)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_5.addWidget(self.spinBox_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.spinBox_5 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_5.setMinimum(-999999999)
        self.spinBox_5.setMaximum(999999999)
        self.spinBox_5.setObjectName("spinBox_5")
        self.verticalLayout_6.addWidget(self.spinBox_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(parent=self)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_4.setMinimum(-99999999.0)
        self.doubleSpinBox_4.setMaximum(99999999.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.spinBox_6 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_6.setMinimum(-999999999)
        self.spinBox_6.setMaximum(999999999)
        self.spinBox_6.setObjectName("spinBox_6")
        self.verticalLayout_7.addWidget(self.spinBox_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(parent=self)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.spinBox_7 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_7.setMinimum(-999999999)
        self.spinBox_7.setMaximum(999999999)
        self.spinBox_7.setObjectName("spinBox_7")
        self.verticalLayout_13.addWidget(self.spinBox_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtWidgets.QLabel(parent=self)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_6.setMinimum(-99999999.0)
        self.doubleSpinBox_6.setMaximum(99999999.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_19 = QtWidgets.QLabel(parent=self)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_19.addWidget(self.label_19)
        self.spinBox_8 = QtWidgets.QSpinBox(parent=self)
        self.spinBox_8.setMinimum(-999999999)
        self.spinBox_8.setMaximum(999999999)
        self.spinBox_8.setObjectName("spinBox_8")
        self.verticalLayout_19.addWidget(self.spinBox_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_19)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_3.setMinimum(-99999999.0)
        self.doubleSpinBox_3.setMaximum(99999999.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(parent=self)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_2.setMinimum(-99999999.0)
        self.doubleSpinBox_2.setMaximum(99999999.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_16 = QtWidgets.QLabel(parent=self)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_16.addWidget(self.label_16)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_8.setMinimum(-99999999.0)
        self.doubleSpinBox_8.setMaximum(99999999.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_8)
        self.horizontalLayout_4.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_17 = QtWidgets.QLabel(parent=self)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_9.setMinimum(-99999999.0)
        self.doubleSpinBox_9.setMaximum(99999999.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.verticalLayout_17.addWidget(self.doubleSpinBox_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_18 = QtWidgets.QLabel(parent=self)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_18.addWidget(self.label_18)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_10.setMinimum(-99999999.0)
        self.doubleSpinBox_10.setMaximum(99999999.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.verticalLayout_18.addWidget(self.doubleSpinBox_10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_18)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtWidgets.QLabel(parent=self)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_7.setMinimum(-99999999.0)
        self.doubleSpinBox_7.setMaximum(99999999.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_20 = QtWidgets.QLabel(parent=self)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_20.addWidget(self.label_20)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_11.setMinimum(-99999999.0)
        self.doubleSpinBox_11.setMaximum(99999999.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.verticalLayout_20.addWidget(self.doubleSpinBox_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_21 = QtWidgets.QLabel(parent=self)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_21.addWidget(self.label_21)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_12.setMinimum(-99999999.0)
        self.doubleSpinBox_12.setMaximum(99999999.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.verticalLayout_21.addWidget(self.doubleSpinBox_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_21)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(parent=self)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox.setMinimum(-99999999.0)
        self.doubleSpinBox.setMaximum(99999999.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_8.addWidget(self.doubleSpinBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(parent=self)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_5.setMinimum(-99999999.0)
        self.doubleSpinBox_5.setMaximum(99999999.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_22 = QtWidgets.QLabel(parent=self)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_22.addWidget(self.label_22)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_13.setMinimum(-99999999.0)
        self.doubleSpinBox_13.setMaximum(99999999.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.verticalLayout_22.addWidget(self.doubleSpinBox_13)
        self.horizontalLayout_5.addLayout(self.verticalLayout_22)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_23 = QtWidgets.QLabel(parent=self)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_23.addWidget(self.label_23)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_14.setMinimum(-99999999.0)
        self.doubleSpinBox_14.setMaximum(99999999.0)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.verticalLayout_23.addWidget(self.doubleSpinBox_14)
        self.horizontalLayout_5.addLayout(self.verticalLayout_23)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_24 = QtWidgets.QLabel(parent=self)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_25.addWidget(self.label_24)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_16.setMinimum(-99999999.0)
        self.doubleSpinBox_16.setMaximum(99999999.0)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.verticalLayout_25.addWidget(self.doubleSpinBox_16)
        self.horizontalLayout_5.addLayout(self.verticalLayout_25)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_25 = QtWidgets.QLabel(parent=self)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_24.addWidget(self.label_25)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_15.setMinimum(-99999999.0)
        self.doubleSpinBox_15.setMaximum(99999999.0)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.verticalLayout_24.addWidget(self.doubleSpinBox_15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_24)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_26 = QtWidgets.QLabel(parent=self)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_26.addWidget(self.label_26)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_17.setMinimum(-99999999.0)
        self.doubleSpinBox_17.setMaximum(99999999.0)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.verticalLayout_26.addWidget(self.doubleSpinBox_17)
        self.horizontalLayout_5.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_27 = QtWidgets.QLabel(parent=self)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_27.addWidget(self.label_27)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(parent=self)
        self.doubleSpinBox_18.setMinimum(-99999999.0)
        self.doubleSpinBox_18.setMaximum(99999999.0)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.verticalLayout_27.addWidget(self.doubleSpinBox_18)
        self.horizontalLayout_5.addLayout(self.verticalLayout_27)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox = QtWidgets.QCheckBox(parent=self)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_6.addWidget(self.checkBox_7)
        self.checkBox_9 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_6.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_6.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_6.addWidget(self.checkBox_11)
        self.checkBox_13 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_6.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_6.addWidget(self.checkBox_14)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_7.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_7.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_7.addWidget(self.checkBox_5)
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_7.addWidget(self.checkBox_8)
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_7.addWidget(self.checkBox_6)
        self.checkBox_15 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_7.addWidget(self.checkBox_15)
        self.checkBox_12 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_7.addWidget(self.checkBox_12)
        self.checkBox_16 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_7.addWidget(self.checkBox_16)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_28 = QtWidgets.QLabel(parent=self)
        self.label_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_28.addWidget(self.label_28)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_17 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_9.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_9.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_9.addWidget(self.checkBox_19)
        self.verticalLayout_28.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_29 = QtWidgets.QLabel(parent=self)
        self.label_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_29.addWidget(self.label_29)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_20 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout_10.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_10.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_10.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_10.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_10.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_10.addWidget(self.checkBox_25)
        self.verticalLayout_29.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_29)
        self.gridLayout.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_30 = QtWidgets.QLabel(parent=self)
        self.label_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_30.addWidget(self.label_30)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_27 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_27.setObjectName("checkBox_27")
        self.horizontalLayout_11.addWidget(self.checkBox_27)
        self.checkBox_28 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_28.setObjectName("checkBox_28")
        self.horizontalLayout_11.addWidget(self.checkBox_28)
        self.checkBox_30 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_30.setObjectName("checkBox_30")
        self.horizontalLayout_11.addWidget(self.checkBox_30)
        self.checkBox_32 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_32.setObjectName("checkBox_32")
        self.horizontalLayout_11.addWidget(self.checkBox_32)
        self.checkBox_33 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_33.setObjectName("checkBox_33")
        self.horizontalLayout_11.addWidget(self.checkBox_33)
        self.checkBox_31 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_31.setObjectName("checkBox_31")
        self.horizontalLayout_11.addWidget(self.checkBox_31)
        self.checkBox_29 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_29.setObjectName("checkBox_29")
        self.horizontalLayout_11.addWidget(self.checkBox_29)
        self.checkBox_26 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_11.addWidget(self.checkBox_26)
        self.verticalLayout_30.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_37 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_37.setObjectName("checkBox_37")
        self.horizontalLayout_12.addWidget(self.checkBox_37)
        self.checkBox_38 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_38.setObjectName("checkBox_38")
        self.horizontalLayout_12.addWidget(self.checkBox_38)
        self.checkBox_39 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_39.setObjectName("checkBox_39")
        self.horizontalLayout_12.addWidget(self.checkBox_39)
        self.checkBox_41 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_41.setObjectName("checkBox_41")
        self.horizontalLayout_12.addWidget(self.checkBox_41)
        self.checkBox_35 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_35.setObjectName("checkBox_35")
        self.horizontalLayout_12.addWidget(self.checkBox_35)
        self.checkBox_34 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_34.setObjectName("checkBox_34")
        self.horizontalLayout_12.addWidget(self.checkBox_34)
        self.checkBox_40 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_40.setObjectName("checkBox_40")
        self.horizontalLayout_12.addWidget(self.checkBox_40)
        self.checkBox_36 = QtWidgets.QCheckBox(parent=self)
        self.checkBox_36.setObjectName("checkBox_36")
        self.horizontalLayout_12.addWidget(self.checkBox_36)
        self.verticalLayout_30.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_30, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self)
        self.pushButton_2.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Добавление пациента"))
        self.label.setText(_translate("Dialog", "Возраст"))
        self.label_2.setText(_translate("Dialog", "Пол"))
        self.comboBox.setItemText(0, _translate("Dialog", "Мужской"))
        self.comboBox.setItemText(1, _translate("Dialog", "Женский"))
        self.label_3.setText(_translate("Dialog", "АД с"))
        self.label_4.setText(_translate("Dialog", "АДД"))
        self.label_5.setText(_translate("Dialog", "ЧДД"))
        self.label_6.setText(_translate("Dialog", "ЧСС"))
        self.label_11.setText(_translate("Dialog", "Температура"))
        self.label_7.setText(_translate("Dialog", "PaO2|FiO2"))
        self.label_13.setText(_translate("Dialog", "SpO2"))
        self.label_14.setText(_translate("Dialog", "Ph"))
        self.label_19.setText(_translate("Dialog", "PAco2"))
        self.label_10.setText(_translate("Dialog", "Тромбоциты"))
        self.label_9.setText(_translate("Dialog", "Лейкоциты"))
        self.label_16.setText(_translate("Dialog", "Гематокрит"))
        self.label_17.setText(_translate("Dialog", "срб"))
        self.label_18.setText(_translate("Dialog", "пкт"))
        self.label_15.setText(_translate("Dialog", "Лактат"))
        self.label_20.setText(_translate("Dialog", "Креатинин"))
        self.label_21.setText(_translate("Dialog", "алт"))
        self.label_8.setText(_translate("Dialog", "Мочевина"))
        self.label_12.setText(_translate("Dialog", "Альбумин"))
        self.label_22.setText(_translate("Dialog", "аст"))
        self.label_23.setText(_translate("Dialog", "мно"))
        self.label_24.setText(_translate("Dialog", "АЧТВ"))
        self.label_25.setText(_translate("Dialog", "птв"))
        self.label_26.setText(_translate("Dialog", "Глюкоза"))
        self.label_27.setText(_translate("Dialog", "Натрий"))
        self.checkBox.setText(_translate("Dialog", "ДН2"))
        self.checkBox_2.setText(_translate("Dialog", "ДН 3"))
        self.checkBox_7.setText(_translate("Dialog", "МБ инфильтрация"))
        self.checkBox_9.setText(_translate("Dialog", "СД"))
        self.checkBox_10.setText(_translate("Dialog", "ХСН"))
        self.checkBox_11.setText(_translate("Dialog", "ХБП"))
        self.checkBox_13.setText(_translate("Dialog", "ЗНО"))
        self.checkBox_14.setText(_translate("Dialog", "ДЭП"))
        self.checkBox_3.setText(_translate("Dialog", "Кома"))
        self.checkBox_4.setText(_translate("Dialog", "Сопор"))
        self.checkBox_5.setText(_translate("Dialog", "Заторможенность"))
        self.checkBox_8.setText(_translate("Dialog", "ХОБЛ"))
        self.checkBox_6.setText(_translate("Dialog", "Вазопрессоры"))
        self.checkBox_15.setText(_translate("Dialog", "Плеврит"))
        self.checkBox_12.setText(_translate("Dialog", "Цирроз печени"))
        self.checkBox_16.setText(_translate("Dialog", "БА"))
        self.label_28.setText(_translate("Dialog", "Кристаллоиды"))
        self.checkBox_17.setText(_translate("Dialog", "КМА"))
        self.checkBox_18.setText(_translate("Dialog", "Рингер"))
        self.checkBox_19.setText(_translate("Dialog", "Поляризующая смесь"))
        self.label_29.setText(_translate("Dialog", "Антибиотик"))
        self.checkBox_20.setText(_translate("Dialog", "Амоксиклав"))
        self.checkBox_21.setText(_translate("Dialog", "Цефтриаксон"))
        self.checkBox_22.setText(_translate("Dialog", "Цефоперазон"))
        self.checkBox_23.setText(_translate("Dialog", "Амоксициллин"))
        self.checkBox_24.setText(_translate("Dialog", "Моксифлоксацин"))
        self.checkBox_25.setText(_translate("Dialog", "Левофлоксацин"))
        self.label_30.setText(_translate("Dialog", "Микрофлора"))
        self.checkBox_27.setText(_translate("Dialog", "E.Coli"))
        self.checkBox_28.setText(_translate("Dialog", "C.Albicans"))
        self.checkBox_30.setText(_translate("Dialog", "Kl. Pneumoniae"))
        self.checkBox_32.setText(_translate("Dialog", "Candida"))
        self.checkBox_33.setText(_translate("Dialog", "Streptococcus"))
        self.checkBox_31.setText(_translate("Dialog", "St. facies"))
        self.checkBox_29.setText(_translate("Dialog", "St. haemolyticus"))
        self.checkBox_26.setText(_translate("Dialog", "β-гемолитический стрептококк"))
        self.checkBox_37.setText(_translate("Dialog", "St.Pnevmoni"))
        self.checkBox_38.setText(_translate("Dialog", "Klebsiella pnevmoni"))
        self.checkBox_39.setText(_translate("Dialog", "Kl. Pneumoniae"))
        self.checkBox_41.setText(_translate("Dialog", "Br. Catarrhalis"))
        self.checkBox_35.setText(_translate("Dialog", "Acinetobacter"))
        self.checkBox_34.setText(_translate("Dialog", "St. aureus"))
        self.checkBox_40.setText(_translate("Dialog", "Enterobacter aerogenes"))
        self.checkBox_36.setText(_translate("Dialog", "Pseudomonas aeruginosa"))
        self.pushButton_2.setText(_translate("Dialog", "Добавить"))
        self.pushButton.setText(_translate("Dialog", "Отмена"))
        self.pushButton.clicked.connect(self.close)
        self.pushButton_2.clicked.connect(self.addData)

    def checkState(self, cb):
        return 1 if cb.checkState() == Qt.CheckState.Checked else 0

    def addData(self):
        age = int(self.spinBox.value())
        sex = 1 if self.comboBox.currentIndex() == 0 else 0
        ADS = int(self.spinBox_2.value())
        ADD = int(self.spinBox_3.value())
        CHDD = int(self.spinBox_4.value())
        CHSS = int(self.spinBox_5.value())
        temprature = float(self.doubleSpinBox_4.value())
        PF = int(self.spinBox_6.value())
        SpO2 = int(self.spinBox_7.value())
        Ph = float(self.doubleSpinBox_6.value())
        PAco2 = int(self.spinBox_8.value())
        tromboc = float(self.doubleSpinBox_3.value())
        leucoc = float(self.doubleSpinBox_2.value())
        gematok = float(self.doubleSpinBox_8.value())
        srb = float(self.doubleSpinBox_9.value())
        pkt = float(self.doubleSpinBox_10.value())
        lactat = float(self.doubleSpinBox_7.value())
        kreatinin = float(self.doubleSpinBox_11.value())
        alt = float(self.doubleSpinBox_12.value())
        urea = float(self.doubleSpinBox.value())
        albumin = float(self.doubleSpinBox_5.value())
        ast = float(self.doubleSpinBox_13.value())
        mno = float(self.doubleSpinBox_14.value())
        ACTV = float(self.doubleSpinBox_16.value())
        ptv = float(self.doubleSpinBox_15.value())
        glucose = float(self.doubleSpinBox_17.value())
        natriy = float(self.doubleSpinBox_18.value())
        DN2 = int(self.checkState(self.checkBox))
        DN3 = int(self.checkState(self.checkBox_2))
        MBInf = int(self.checkState(self.checkBox_7))
        SD = int(self.checkState(self.checkBox_9))
        HSN = int(self.checkState(self.checkBox_10))
        HBP = int(self.checkState(self.checkBox_11))
        ZNO = int(self.checkState(self.checkBox_13))
        DEP = int(self.checkState(self.checkBox_14))
        koma = int(self.checkState(self.checkBox_3))
        Sopor = int(self.checkState(self.checkBox_4))
        breaking = int(self.checkState(self.checkBox_5))
        HOBL = int(self.checkState(self.checkBox_8))
        vazopre = int(self.checkState(self.checkBox_6))
        plevrit = int(self.checkState(self.checkBox_15))
        cirpec = int(self.checkState(self.checkBox_12))
        BA = int(self.checkState(self.checkBox_16))
        kristalloid = ''
        kristalloidCB = [self.checkBox_17, self.checkBox_18, self.checkBox_19]
        for i in kristalloidCB:
            if i.checkState() == Qt.CheckState.Checked:
                if kristalloid != '' and i != self.checkBox_17:
                    kristalloid += ', '
                kristalloid += i.text()
        antibiotik = ''
        antibiotikCB = [self.checkBox_20, self.checkBox_21, self.checkBox_22, self.checkBox_23, self.checkBox_24,
                        self.checkBox_25]
        for i in antibiotikCB:
            if i.checkState() == Qt.CheckState.Checked:
                if antibiotik != '' and i != self.checkBox_20:
                    antibiotik += ', '
                antibiotik += i.text()
        microflora = ''
        microfloraCB = [self.checkBox_26, self.checkBox_27, self.checkBox_28, self.checkBox_29, self.checkBox_30,
                        self.checkBox_31, self.checkBox_32, self.checkBox_33, self.checkBox_34, self.checkBox_35,
                        self.checkBox_36, self.checkBox_37, self.checkBox_38, self.checkBox_39, self.checkBox_40,
                        self.checkBox_41]
        for i in microfloraCB:
            if i.checkState() == Qt.CheckState.Checked:
                if microflora != '' and i != self.checkBox_26:
                    microflora += ', '
                microflora += i.text()
        db = dbret()
        cur = db.cursor()
        sql = ("INSERT INTO patients (num, age, sex, DN2, DN3, ADS, patients.ADD, CHDD, PaO2FiO2, Koma, Sopor, "
               "Retardation,"
               "Urea, Leukocytes, Platelets, Temperature, Crystalloids, Vasopressors, Multilobar_infiltration, "
               "Albumen, CHSS, SpO2, Ph, Lactate, Microflora, Гематокрит, SRB, PKT, PAco2, Creatine, ALT, AST, MNO, "
               "PTV, ACHTV, HOBL, SD, HSN, HBP, Cirrhosis, Antibiotic, ZNO, DEP, Glucose, Sodium, Pleurisy, BA) VALUES "
               "(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, '%s', %s, %s, %s, %s, %s, %s, %s, %s, "
               "%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)")
        cur.execute("select max(num) from patients")
        num = int(cur.fetchall()[0][0]) + 1
        val = (num, age, sex, DN2, DN3, ADS, ADD, CHDD, PF, koma, Sopor, breaking, urea, leucoc, tromboc, temprature,
                kristalloid, vazopre, MBInf, albumin, CHSS, SpO2, Ph, lactat, microflora, gematok, srb, pkt, PAco2,
                kreatinin, alt, ast, mno, ptv, ACTV, HOBL, SD, HSN, HBP, cirpec, antibiotik, ZNO, DEP, glucose, natriy,
                plevrit, BA)
        cur.execute(sql, val)
        db.commit()
        db.close()
        self.close()
